// Generated by scripts/build-articles.mjs. Do not edit manually.
const PRECACHE_VERSION = "fbaba0cf7c729afa";
const PRECACHE_FILES = [
  "app.js",
  "article.html",
  "article.js",
  "assets/app-icon-180.png",
  "assets/app-icon-192.png",
  "assets/app-icon-512.png",
  "assets/app-icon.svg",
  "assets/four-golden-signals-cover.jpg",
  "assets/leases-e-fencing-tokens-cover.jpg",
  "assets/quoruns-de-leitura-e-escrita-cover.jpg",
  "assets/transactional-outbox-cover.jpg",
  "content/articles/four-golden-signals.json",
  "content/articles/index.json",
  "content/articles/leases-e-fencing-tokens.json",
  "content/articles/quoruns-de-leitura-e-escrita.json",
  "content/articles/transactional-outbox.json",
  "fgs-simulator.js",
  "index.html",
  "manifest.webmanifest",
  "pwa.js",
  "styles.css"
];
