// Generated by scripts/build-articles.mjs. Do not edit manually.
const PRECACHE_VERSION = "f2b4e982f2ad19ac";
const PRECACHE_FILES = [
  "app.js",
  "article.html",
  "article.js",
  "assets/app-icon-180.png",
  "assets/app-icon-192.png",
  "assets/app-icon-512.png",
  "assets/app-icon.svg",
  "assets/four-golden-signals-cover.jpg",
  "content/articles/four-golden-signals.json",
  "content/articles/index.json",
  "index.html",
  "manifest.webmanifest",
  "pwa.js",
  "styles.css"
];
